name: postgres-example
channels:
  - defaults
  - conda-forge
dependencies:
  - postgresql
  - psycopg2
  - pip
  - pip:
    - pandas
    - git+https://github.com/catherinedevlin/ipython-sql.git
  - r-base=3.6
  - r-tidyverse
